### ISSUE TITLE
Error installing on Kali

### ISSUE THREAD

**Issue by jcmoreno** [JonnyHightower/neet#4]
Hi,

I'm getting the following error while installing on Kali 2 (rolling):
Can't locate checkdeps.pm in @INC (you may need to install the checkdeps module) (@INC contains: /etc/perl /usr/local/lib/i386-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/i386-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base) at ./checkdeps.pl line 26.
BEGIN failed--compilation aborted at ./checkdeps.pl line 26.

I'm not a Perl whiz, but I see that the checkdeps.pm is on the same directory as the checkdeps.pl, so I don't know why it's not finding it...

Any ideas?

**Comment by jcmoreno** [comment]
selectDistro returns kali-kali-rolling which is not in "content/install/pkg/", so it was defaulting to ubuntu-14.04

I forced it to "kali", but still the same error.

**Comment by JonnyHightower** [comment]
Hi. Thanks for this. I haven't tested this on Kali for a couple of years. If checkdeps.pl couldn't find checkdeps.pm, then it means the current directory wasn't in @INC. You can add the current directory to @INC by adding the following line near the top of checkdeps.pl:
`push @INC, ".";`
I'll do this in the next release, which will be coming up next week.

**Comment by marcobelmonte** [comment]
this didn't fix my issue - I'm on Debian Sid and get the same error. Of course, using Sid is my problem and not yours but thought I'd see if anyone knew how to solve the problem anyways ;-)

**Comment by JonnyHightower** [comment]
Hey Marco. I haven't actually tested it on Debian - I was relying on it being fairly similar (in terms of package names) to Ubuntu. I'm downloading an ISO of Sid (and stable) and will see if I can figure out what's going on. Cheers.

**Comment by JonnyHightower** [comment]
Sid won't even *install* in my VM - after the disk setup, installation of the base system fails immediately because of an error in one of the boostrap scripts. I'm installing the stable version now, and that's going fine. I'd forgotten just how edgy Sid can be. I'll test Neet on the current stable version (Jessie), but I haven't got time to mess about with Sid sorry.

**Comment by marcobelmonte** [comment]
ya, I went from testing and then upgraded to stable so I wasn't aware that the installer is messed up. I always tells myself that I won't migrate to Sid no matter what and then everytime - sometimes even a year or so later - there is some package that has a feature or bug fix in it and you know what they say about apt-pinning, etc.... anyways... I'll stop with the war stories... I'll try and figure it out and post a solution on this thread. It's weird, the exact same error as OP and yet you've already released the fix to your GIT repo and for some reason it doesn't see the perl module. It has to be something simple.

**Comment by JonnyHightower** [comment]
This is fixed for Kali and Debian stable in the latest release.
