### ISSUE TITLE
mainscan.pm 

### ISSUE THREAD

**Issue by mathieuchot** [JonnyHightower/neet#5]
157     # Record interface information
 158     my $if;
 159     for my $line (`/sbin/ifconfig -a`){
 160         if ($line =~ /^\w+\d+[\.\d+]{0,}\s+Link[\s\S]+/){
 161             $if=$line; $if =~ s/^(\w+\d+[\.\d+]{0,})\s+Link[\s\S]+/$1/;
 162         }
 163         if ($line =~ /inet addr/){
 
On Debian the result of ifconfig is not the same, I had to replace line 163 to 'if ($line =~ /inet adr/){' to make it work.

**Comment by JonnyHightower** [comment]
Really? Which version of Debian was this?

**Comment by JonnyHightower** [comment]
Thanks for letting me know :+1:

**Comment by mathieuchot** [comment]
3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
