### ISSUE TITLE
ERROR: No configured network interfaces found. Exiting.

### ISSUE THREAD

**Issue by 007scorpio** [JonnyHightower/neet#6]
Hi, Jonney, after a successful installation of your tool on kali, it complains of not having a network interface configured with the following error code:
ERROR: No configured network interfaces found. Exiting.

Please what can i do to resolve this...

**Comment by GeneralBison** [comment]
Looks to be a problem with how ifconfig is displaying interface information
[Link](https://github.com/JonnyHightower/neet/blob/9ae756143df8718bd8571048e721567f7274bdb5/content/main/bin/netconfig#L30)

Has problems at lines 44-46 too, currently working out my own messy solution.

**Comment by JonnyHightower** [comment]
As GeneralBison said, this is an issue with the way ifconfig's out has changed in Kali. Working on a fix.

**Comment by jcmoreno** [comment]
Great! I was also facing this issue, and I wasn't sure if it was just me or not.

**Comment by JonnyHightower** [comment]
Fixed in the latest release hopefully!
