### ISSUE TITLE
Error while trying to scan a single host

### ISSUE THREAD

**Issue by M1chael** [JonnyHightower/neet#8]
I try to scan a single host both with "-I" option and without it. After "Starting Service Discovery" neet exit with error:
`Can't call method "contains" on an undefined value at /opt/neet/core/Neet/MainScan.pm line 974.`.
OS: Debian 8

**Comment by JonnyHightower** [comment]
Hi M1chael,
It works fine for me on Debian 8. Can you run neet-update and try again please? If you still get the same error, please send me the output of the following commands:

- /sbin/ip addr show
- /sbin/route -n
- the entire command line you used to start Neet.

Thanks!

**Comment by M1chael** [comment]
Hello Jonny.
Thanks for reply! `neet-update` was my first try. It didn't help.

    /sbin/ip addr show
    35: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 5e:48:6f:66:63:24 brd ff:ff:ff:ff:ff:ff
    inet 10.<x>.<y>.8/24 brd 10.<x>.<y>.255 scope global eth0
    inet6 fe80::5c48:6fff:fe66:6324/64 scope link 
    valid_lft forever preferred_lft forever
    37: lo: <LOOPBACK,UP,LOWER_UP> mtu 16436 qdisc noqueue state UNKNOWN group default 
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
    inet6 ::1/128 scope host 
    valid_lft forever preferred_lft forever

    /sbin/route -n
    Kernel IP routing table
    Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
    0.0.0.0         10.<x>.<y>.1    0.0.0.0         UG    0      0        0 eth0
    10.<x>.<y>.0    0.0.0.0         255.255.255.0   U     0      0        0 eth0

    neet -I 176.9.<a>.<b>
    neet 176.9.<a>.<b>

**Comment by JonnyHightower** [comment]
Thank you. My fault! To fix it, edit _/opt/neet/core/Neet/MainScan.pm_. In line 322, replace:
_if ($line =~ /^\d:/){_
with
_if ($line =~ /^\d+:/){_
I'll get a new release pushed out shortly. Thanks for letting me know!

**Comment by M1chael** [comment]
Perfect! It works! Thanks for the so fast fix!
