### ISSUE TITLE
Successful installation but can't run script 

### ISSUE THREAD

**Issue by 007scorpio** [JonnyHightower/neet#9]
Can't call method "contains" on an undefined value at /opt/neet/core/Neet/MainScan.pm line 974.

**Comment by JonnyHightower** [comment]
Hi 007scorpio. This appears to be the same as issue #8 which is already fixed and closed. Please run neet-update (or neet --update) and then try again, then let me know if that worked.
Cheers,
Jon

**Comment by JonnyHightower** [comment]
Please send me the following:

- The output of "ip addr show"
- The output of "route -n"
- The full command line you used to start neet when it failed.

Thanks!

**Comment by 007scorpio** [comment]
ip addr show:
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:a4:e7:df brd ff:ff:ff:ff:ff:ff
    inet 10.152.152.12/24 brd 10.152.152.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::816f:454f:8569:887d/64 scope link 
       valid_lft forever preferred_lft forever
4: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none 
    inet 10.211.1.17 peer 10.211.1.18/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::f04a:c906:dc25:c007/64 scope link flags 800 
       valid_lft forever preferred_lft forever

Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.211.x.x     128.0.0.0       UG    0      0        0 tun0
0.0.0.0         10.152.x.x     0.0.0.0         UG    100    0        0 eth0
10.152.x.x      0.0.0.0         255.255.255.0   U     100    0        0 eth0
10.211.x.x      0.0.0.0         255.255.255.255 UH    0      0        0 tun0
128.0.0.0       10.211.x.x     128.0.0.0       UG    0      0        0 tun0
186.38.x.x     10.152.x.x      255.255.255.255 UGH   0      0        0 eth0

Neet full command:

neet -I 196.x.x.x-255

**Comment by JonnyHightower** [comment]
OK - thanks. I see what it is. I haven't tested it with a PTP link since the other day when I changed how it read the IP configuration. Should have a fix out very soon.

**Comment by 007scorpio** [comment]
Thanks dude u are awesome... Neet is a great tool.

**Comment by JonnyHightower** [comment]
Thanks :+1: Can you try neet-update now and see if it's fixed please?

**Comment by 007scorpio** [comment]
ok it was using the PTP interface by default so i ifconfig it down to use eth0 interface and now it working.

**Comment by JonnyHightower** [comment]
OK. It should now also work if you need to test something over that tun0 interface. Could you test that if you get a chance please? I don't have a PTP endpoint handy at the moment. Thanks!

**Comment by 007scorpio** [comment]
ok i will and let u know pls.  Thanks dude.

**Comment by JonnyHightower** [comment]
:+1:

**Comment by 007scorpio** [comment]
PTP is working now but on my kali rolling it says it can't find metasploit installation

**Comment by JonnyHightower** [comment]
Cool - thanks for testing with the PTP link!
The metasploit installation is already an open issue - #7, opened by you :-p I'll close this one now, as it's more specifically about your PTP interface issue that is now fixed. We'll keep #7 open as it includes the metasploit problem. Cheers!
